module.exports = {
  JAVASCRIPT: "javascript",
  GO: "go",
  RUST: "rust",
  C: "c",
  CPP: "cpp",
  PYTHON: "python",
  JAVA: "java",
  NODEJS: "nodejs",
  RUBY: "ruby",
  PROMPTV1: "promptv1",
  PROMPTV2: "promptv2",
  MULTIFILE: "multifile",
  SQLITE3: "sqlite3",
};
